apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPNAME}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${APPNAME}
  template:
    metadata:
      labels:
        app: ${APPNAME}
    spec:
      containers:
      - image: gcr.io/${PROJECT}/${APPNAME}:${TAG}
        name: ${APPNAME}
        env:
          - name: SLEEP
            valueFrom:
              configMapKeyRef:
                name: api-params
                key: SLEEP
          - name: RAND_DIV
            valueFrom:
              configMapKeyRef:
                name: api-params
                key: RAND_DIV
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/backend-config: '{"default": "custom-health-check"}'

  labels:
    app: ${APPNAME}
  name: ${APPNAME}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ${APPNAME}
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APPNAME}
  # annotations:
  #   kubernetes.io/ingress.global-static-ip-name: ${APPNAME}
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${APPNAME}
            port:
              number: 80
          # serviceName: ${APPNAME}
          # servicePort: 80apiVersion: v1
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: custom-health-check
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8080
    type: HTTP
    requestPath: /test
---
apiVersion: v1
data:
  SLEEP: ""
  RAND500DIV: "${RAND}"
  DUMMY: ""
kind: ConfigMap
metadata:
  name: api-params
  namespace: default
