apiVersion: monitoring.googleapis.com/v1alpha1
kind: PodMonitoring
metadata:
  name: any-method-api
spec:
  selector:
    matchLabels:
      app: any-method-api
  endpoints:
  - port: monitor
    interval: 30s
